### ISSUE TITLE
Cannot pull latest version

### ISSUE THREAD

**Issue by anthonyangel** [dchesterton/texecom2mqtt-hassio#15]
**Describe the bug**
When pulling the latest version I'm getting supervisor errors, looks like the default branch is called `main`, but the supervisor is looking for `master`

**Home Assistant version**
supervisor-2021.02.9

**Debug log**
```
21-02-15 15:06:29 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/dchesterton/texecom2mqtt-hassio repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: couldn't find remote ref refs/heads/master'.
21-02-15 15:06:30 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-1813' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:101> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 796, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 674, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.8/site-packages/git/cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: couldn't find remote ref refs/heads/master'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 105, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 63, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 61, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 195, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError

```

**Comment by dchesterton** [comment]
This should now be fixed

**Comment by RogerSelwyn** [comment]
Now that you have swapped to Main I get the following error in my logs. I think it is just the same but with main instead of master. I suspect HA supports both, but something isn't quite right in your repository.

```
21-02-16 08:26:52 ERROR (MainThread) [supervisor.store.git] Can't update https://github.com/dchesterton/texecom2mqtt-hassio repo: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: couldn't find remote ref refs/heads/main'.
21-02-16 08:26:52 ERROR (MainThread) [asyncio] Task exception was never retrieved
future: <Task finished name='Task-86515' coro=<Repository.update() done, defined at /usr/src/supervisor/supervisor/store/repository.py:101> exception=StoreGitError()>
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/git.py", line 155, in pull
    await self.sys_run_in_executor(
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 796, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/usr/local/lib/python3.8/site-packages/git/remote.py", line 674, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.8/site-packages/git/cmd.py", line 408, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch --depth=1 --update-shallow -v origin
  stderr: 'fatal: couldn't find remote ref refs/heads/main'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/usr/src/supervisor/supervisor/store/repository.py", line 105, in update
    await self.git.pull()
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 63, in wrapper
    raise err
  File "/usr/src/supervisor/supervisor/jobs/decorator.py", line 61, in wrapper
    return await self._method(*args, **kwargs)
  File "/usr/src/supervisor/supervisor/store/git.py", line 195, in pull
    raise StoreGitError() from err
supervisor.exceptions.StoreGitError
```

**Comment by RogerSelwyn** [comment]
Looks like if I uninstall, delete and re-add repository and re-install, it sorts it out.
