### ISSUE TITLE
Communication Issue - V5.05

### ISSUE THREAD

**Issue by tom1422** [dchesterton/texecom2mqtt-hassio#29]
**Describe the bug**
When trying to connect to the panel I get a login issue. After changing the UDL password from a number to a string, it appears to resolve itself until I get an unexpected start error (a few seconds after it connects). Is it an issue with V5.05 or could it be fixed?

**Application version**
1.1.5

**Texecom alarm type**
Premier Elite 48

**Home Assistant version**
core-2021.9.7 - OS 6.4

**Debug log**
`2021-09-22 21:04:01 - INFO: Fetched panel info: Premier Elite 48 (V5.05.00LS1)
2021-09-22 21:04:01 - TRACE: Executing command 25
2021-09-22 21:04:01 - TRACE: Received data chunk of length 11
2021-09-22 21:04:01 - DEBUG: Publishing to texecom2mqtt/power: {"battery_charging_current":0,"battery_voltage":13.63,"panel_current":261,"panel_voltage":13.63}
2021-09-22 21:04:01 - TRACE: Executing command 37
2021-09-22 21:04:01 - TRACE: Received data chunk of length 7
2021-09-22 21:04:01 - TRACE: Executing command 34
2021-09-22 21:04:02 - TRACE: Received data chunk of length 70
2021-09-22 21:04:02 - INFO: Fetched Area A: Area A
2021-09-22 21:04:02 - INFO: Fetched Area B: Area B
2021-09-22 21:04:02 - INFO: Fetched Area C: Area C
2021-09-22 21:04:02 - INFO: Fetched Area D: Area D
2021-09-22 21:04:02 - TRACE: Executing command 3
2021-09-22 21:04:02 - TRACE: Received data chunk of length 14
/snapshot/app/dist/texecom/texecom.js:81
            throw new Error(`Unexpected start, expected 't', got 0x${headerStart.toString(16)}`);
            ^
Error: Unexpected start, expected 't', got 0x78
    at Texecom.parseBuffer (/snapshot/app/dist/texecom/texecom.js:81:19)
    at Socket.<anonymous> (/snapshot/app/dist/texecom/texecom.js:32:18)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:271:9)
    at Socket.Readable.push (_stream_readable.js:212:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)`

**Comment by tom1422** [comment]
Downgraded to V5.02 and its working now.
